//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOnAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int CartID { get; set; }
        public int CartStockID { get; set; }
        public int CartQuantity { get; set; }
        public double CartUnitCost { get; set; }
        public string CartClientID { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
