//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOnAPIs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class enigma_gameonEntities : DbContext
    {
        public enigma_gameonEntities()
            : base("name=enigma_gameonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Review> Reviews { get; set; }
        public virtual DbSet<Size> Sizes { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<SubCategory> SubCategories { get; set; }
        public virtual DbSet<UserDetail> UserDetails { get; set; }
    
        public virtual int sp_category_delete(Nullable<int> category_id)
        {
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_category_delete", category_idParameter);
        }
    
        public virtual ObjectResult<sp_category_get_all_Result> sp_category_get_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_category_get_all_Result>("sp_category_get_all");
        }
    
        public virtual ObjectResult<sp_category_get_all_by_department_id_Result> sp_category_get_all_by_department_id(Nullable<int> department_id)
        {
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_category_get_all_by_department_id_Result>("sp_category_get_all_by_department_id", department_idParameter);
        }
    
        public virtual int sp_category_insert(string category_name, Nullable<int> department_id)
        {
            var category_nameParameter = category_name != null ?
                new ObjectParameter("category_name", category_name) :
                new ObjectParameter("category_name", typeof(string));
    
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_category_insert", category_nameParameter, department_idParameter);
        }
    
        public virtual int sp_category_update(Nullable<int> category_id, string category_name, Nullable<int> department_id)
        {
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            var category_nameParameter = category_name != null ?
                new ObjectParameter("category_name", category_name) :
                new ObjectParameter("category_name", typeof(string));
    
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_category_update", category_idParameter, category_nameParameter, department_idParameter);
        }
    
        public virtual int sp_delete_cart_details_by_cart_id(string cart_id)
        {
            var cart_idParameter = cart_id != null ?
                new ObjectParameter("cart_id", cart_id) :
                new ObjectParameter("cart_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_delete_cart_details_by_cart_id", cart_idParameter);
        }
    
        public virtual int sp_department_delete(Nullable<int> department_id)
        {
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_department_delete", department_idParameter);
        }
    
        public virtual ObjectResult<sp_department_get_all_Result> sp_department_get_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_department_get_all_Result>("sp_department_get_all");
        }
    
        public virtual ObjectResult<sp_department_get_by_id_Result> sp_department_get_by_id(Nullable<int> department_id)
        {
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_department_get_by_id_Result>("sp_department_get_by_id", department_idParameter);
        }
    
        public virtual int sp_department_insert(string department_name)
        {
            var department_nameParameter = department_name != null ?
                new ObjectParameter("department_name", department_name) :
                new ObjectParameter("department_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_department_insert", department_nameParameter);
        }
    
        public virtual int sp_department_update(Nullable<int> department_id, string department_name)
        {
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            var department_nameParameter = department_name != null ?
                new ObjectParameter("department_name", department_name) :
                new ObjectParameter("department_name", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_department_update", department_idParameter, department_nameParameter);
        }
    
        public virtual ObjectResult<sp_get_all_categories_by_department_id_Result> sp_get_all_categories_by_department_id(Nullable<int> department_id)
        {
            var department_idParameter = department_id.HasValue ?
                new ObjectParameter("department_id", department_id) :
                new ObjectParameter("department_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_all_categories_by_department_id_Result>("sp_get_all_categories_by_department_id", department_idParameter);
        }
    
        public virtual ObjectResult<sp_get_all_sub_categories_by_category_id_Result> sp_get_all_sub_categories_by_category_id(Nullable<int> category_id)
        {
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_all_sub_categories_by_category_id_Result>("sp_get_all_sub_categories_by_category_id", category_idParameter);
        }
    
        public virtual ObjectResult<sp_get_cart_details_by_user_id_Result> sp_get_cart_details_by_user_id(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_cart_details_by_user_id_Result>("sp_get_cart_details_by_user_id", user_idParameter);
        }
    
        public virtual ObjectResult<sp_get_colours_by_product_id_Result> sp_get_colours_by_product_id(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_colours_by_product_id_Result>("sp_get_colours_by_product_id", product_idParameter);
        }
    
        public virtual ObjectResult<sp_get_images_by_product_id_Result> sp_get_images_by_product_id(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_images_by_product_id_Result>("sp_get_images_by_product_id", product_idParameter);
        }
    
        public virtual ObjectResult<sp_get_product_details_by_id_Result> sp_get_product_details_by_id(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_product_details_by_id_Result>("sp_get_product_details_by_id", product_idParameter);
        }
    
        public virtual ObjectResult<sp_get_recently_added_products_Result> sp_get_recently_added_products()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_recently_added_products_Result>("sp_get_recently_added_products");
        }
    
        public virtual ObjectResult<sp_get_sizes_by_product_id_Result> sp_get_sizes_by_product_id(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_sizes_by_product_id_Result>("sp_get_sizes_by_product_id", product_idParameter);
        }
    
        public virtual ObjectResult<sp_get_stock_by_product_id_color_id_size_id_Result> sp_get_stock_by_product_id_color_id_size_id(Nullable<int> product_id, Nullable<int> color_id, Nullable<int> size_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var color_idParameter = color_id.HasValue ?
                new ObjectParameter("color_id", color_id) :
                new ObjectParameter("color_id", typeof(int));
    
            var size_idParameter = size_id.HasValue ?
                new ObjectParameter("size_id", size_id) :
                new ObjectParameter("size_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_stock_by_product_id_color_id_size_id_Result>("sp_get_stock_by_product_id_color_id_size_id", product_idParameter, color_idParameter, size_idParameter);
        }
    
        public virtual ObjectResult<sp_get_top_three_products_by_category_id_Result> sp_get_top_three_products_by_category_id(Nullable<int> category_id)
        {
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_top_three_products_by_category_id_Result>("sp_get_top_three_products_by_category_id", category_idParameter);
        }
    
        public virtual ObjectResult<sp_get_top_three_products_by_sub_category_id_Result> sp_get_top_three_products_by_sub_category_id(Nullable<int> sub_category_id)
        {
            var sub_category_idParameter = sub_category_id.HasValue ?
                new ObjectParameter("sub_category_id", sub_category_id) :
                new ObjectParameter("sub_category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_get_top_three_products_by_sub_category_id_Result>("sp_get_top_three_products_by_sub_category_id", sub_category_idParameter);
        }
    
        public virtual int sp_insert_into_cart(Nullable<int> stock_id, Nullable<int> quantity, Nullable<double> unitCost, string userID)
        {
            var stock_idParameter = stock_id.HasValue ?
                new ObjectParameter("stock_id", stock_id) :
                new ObjectParameter("stock_id", typeof(int));
    
            var quantityParameter = quantity.HasValue ?
                new ObjectParameter("quantity", quantity) :
                new ObjectParameter("quantity", typeof(int));
    
            var unitCostParameter = unitCost.HasValue ?
                new ObjectParameter("unitCost", unitCost) :
                new ObjectParameter("unitCost", typeof(double));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_into_cart", stock_idParameter, quantityParameter, unitCostParameter, userIDParameter);
        }
    
        public virtual int sp_product_delete(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_product_delete", product_idParameter);
        }
    
        public virtual ObjectResult<sp_product_get_all_Result> sp_product_get_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_product_get_all_Result>("sp_product_get_all");
        }
    
        public virtual ObjectResult<sp_product_get_all_by_sub_category_id_Result> sp_product_get_all_by_sub_category_id(Nullable<int> sub_category_id)
        {
            var sub_category_idParameter = sub_category_id.HasValue ?
                new ObjectParameter("sub_category_id", sub_category_id) :
                new ObjectParameter("sub_category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_product_get_all_by_sub_category_id_Result>("sp_product_get_all_by_sub_category_id", sub_category_idParameter);
        }
    
        public virtual int sp_product_insert(string product_name, string product_description, Nullable<double> product_price, string product_thumbnail, Nullable<int> product_sub_category_id)
        {
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var product_descriptionParameter = product_description != null ?
                new ObjectParameter("product_description", product_description) :
                new ObjectParameter("product_description", typeof(string));
    
            var product_priceParameter = product_price.HasValue ?
                new ObjectParameter("product_price", product_price) :
                new ObjectParameter("product_price", typeof(double));
    
            var product_thumbnailParameter = product_thumbnail != null ?
                new ObjectParameter("product_thumbnail", product_thumbnail) :
                new ObjectParameter("product_thumbnail", typeof(string));
    
            var product_sub_category_idParameter = product_sub_category_id.HasValue ?
                new ObjectParameter("product_sub_category_id", product_sub_category_id) :
                new ObjectParameter("product_sub_category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_product_insert", product_nameParameter, product_descriptionParameter, product_priceParameter, product_thumbnailParameter, product_sub_category_idParameter);
        }
    
        public virtual int sp_product_update(Nullable<int> product_id, string product_name, string product_description, Nullable<double> product_price, string product_thumbnail, Nullable<int> product_sub_category_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            var product_nameParameter = product_name != null ?
                new ObjectParameter("product_name", product_name) :
                new ObjectParameter("product_name", typeof(string));
    
            var product_descriptionParameter = product_description != null ?
                new ObjectParameter("product_description", product_description) :
                new ObjectParameter("product_description", typeof(string));
    
            var product_priceParameter = product_price.HasValue ?
                new ObjectParameter("product_price", product_price) :
                new ObjectParameter("product_price", typeof(double));
    
            var product_thumbnailParameter = product_thumbnail != null ?
                new ObjectParameter("product_thumbnail", product_thumbnail) :
                new ObjectParameter("product_thumbnail", typeof(string));
    
            var product_sub_category_idParameter = product_sub_category_id.HasValue ?
                new ObjectParameter("product_sub_category_id", product_sub_category_id) :
                new ObjectParameter("product_sub_category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_product_update", product_idParameter, product_nameParameter, product_descriptionParameter, product_priceParameter, product_thumbnailParameter, product_sub_category_idParameter);
        }
    
        public virtual int sp_sub_category_delete(Nullable<int> sub_category_id)
        {
            var sub_category_idParameter = sub_category_id.HasValue ?
                new ObjectParameter("sub_category_id", sub_category_id) :
                new ObjectParameter("sub_category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sub_category_delete", sub_category_idParameter);
        }
    
        public virtual ObjectResult<sp_sub_category_get_all_Result> sp_sub_category_get_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sub_category_get_all_Result>("sp_sub_category_get_all");
        }
    
        public virtual ObjectResult<sp_sub_category_get_all_by_category_id_Result> sp_sub_category_get_all_by_category_id(Nullable<int> category_id)
        {
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_sub_category_get_all_by_category_id_Result>("sp_sub_category_get_all_by_category_id", category_idParameter);
        }
    
        public virtual int sp_sub_category_insert(string sub_category_name, Nullable<int> category_id)
        {
            var sub_category_nameParameter = sub_category_name != null ?
                new ObjectParameter("sub_category_name", sub_category_name) :
                new ObjectParameter("sub_category_name", typeof(string));
    
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sub_category_insert", sub_category_nameParameter, category_idParameter);
        }
    
        public virtual int sp_sub_category_update(Nullable<int> sub_category_id, string sub_category_name, Nullable<int> category_id)
        {
            var sub_category_idParameter = sub_category_id.HasValue ?
                new ObjectParameter("sub_category_id", sub_category_id) :
                new ObjectParameter("sub_category_id", typeof(int));
    
            var sub_category_nameParameter = sub_category_name != null ?
                new ObjectParameter("sub_category_name", sub_category_name) :
                new ObjectParameter("sub_category_name", typeof(string));
    
            var category_idParameter = category_id.HasValue ?
                new ObjectParameter("category_id", category_id) :
                new ObjectParameter("category_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_sub_category_update", sub_category_idParameter, sub_category_nameParameter, category_idParameter);
        }
    
        public virtual int sp_user_delete(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_user_delete", user_idParameter);
        }
    
        public virtual ObjectResult<sp_user_find_by_username_password_Result> sp_user_find_by_username_password(string user_username, string user_password)
        {
            var user_usernameParameter = user_username != null ?
                new ObjectParameter("user_username", user_username) :
                new ObjectParameter("user_username", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_find_by_username_password_Result>("sp_user_find_by_username_password", user_usernameParameter, user_passwordParameter);
        }
    
        public virtual ObjectResult<sp_user_get_all_Result> sp_user_get_all()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_get_all_Result>("sp_user_get_all");
        }
    
        public virtual ObjectResult<sp_user_get_by_id_Result> sp_user_get_by_id(string user_id)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_user_get_by_id_Result>("sp_user_get_by_id", user_idParameter);
        }
    
        public virtual int sp_user_insert(string user_userID, string user_username, string user_password, string user_email, string user_phone)
        {
            var user_userIDParameter = user_userID != null ?
                new ObjectParameter("user_userID", user_userID) :
                new ObjectParameter("user_userID", typeof(string));
    
            var user_usernameParameter = user_username != null ?
                new ObjectParameter("user_username", user_username) :
                new ObjectParameter("user_username", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var user_phoneParameter = user_phone != null ?
                new ObjectParameter("user_phone", user_phone) :
                new ObjectParameter("user_phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_user_insert", user_userIDParameter, user_usernameParameter, user_passwordParameter, user_emailParameter, user_phoneParameter);
        }
    
        public virtual int sp_user_update(string user_id, string user_username, string user_password, string user_email, string user_phone)
        {
            var user_idParameter = user_id != null ?
                new ObjectParameter("user_id", user_id) :
                new ObjectParameter("user_id", typeof(string));
    
            var user_usernameParameter = user_username != null ?
                new ObjectParameter("user_username", user_username) :
                new ObjectParameter("user_username", typeof(string));
    
            var user_passwordParameter = user_password != null ?
                new ObjectParameter("user_password", user_password) :
                new ObjectParameter("user_password", typeof(string));
    
            var user_emailParameter = user_email != null ?
                new ObjectParameter("user_email", user_email) :
                new ObjectParameter("user_email", typeof(string));
    
            var user_phoneParameter = user_phone != null ?
                new ObjectParameter("user_phone", user_phone) :
                new ObjectParameter("user_phone", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_user_update", user_idParameter, user_usernameParameter, user_passwordParameter, user_emailParameter, user_phoneParameter);
        }
    }
}
