//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOnAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public int OrderStockID { get; set; }
        public int OrderQuantity { get; set; }
        public double OrderUnitCost { get; set; }
        public string OrderUserID { get; set; }
        public System.DateTime OrderDateCreated { get; set; }
        public Nullable<System.DateTime> OrderDateShipped { get; set; }
        public Nullable<System.DateTime> OrderDateDelivered { get; set; }
        public Nullable<System.DateTime> OderDateCancelled { get; set; }
        public string OrderComments { get; set; }
        public string OrderUserName { get; set; }
        public string OrderPhone { get; set; }
        public string OrderAddress1 { get; set; }
        public string OrderAddress2 { get; set; }
        public string OrderCity { get; set; }
        public string OrderProvince { get; set; }
        public string OrderCountry { get; set; }
        public string OrderPostalCode { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
