//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOnAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Images = new HashSet<Image>();
            this.Reviews = new HashSet<Review>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductDescription { get; set; }
        public double ProductPrice { get; set; }
        public int ProductSubCategoryID { get; set; }
        public string ProductThumbnail { get; set; }
    
        public virtual ICollection<Image> Images { get; set; }
        public virtual SubCategory SubCategory { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
