//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOnAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ReviewID { get; set; }
        public string Review1 { get; set; }
        public int ReviewProductID { get; set; }
        public Nullable<int> ReviewRating { get; set; }
        public string ReviewUserID { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
