//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameOnAPIs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stock
    {
        public Stock()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
        }
    
        public int StockID { get; set; }
        public int StockProductID { get; set; }
        public int StockColorID { get; set; }
        public int StockSizeID { get; set; }
        public int StockQuantityAvailable { get; set; }
    
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Color Color { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
